version=v50

python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_2030_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_2030_${version}.root --x 5534000  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_3050_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_3050_${version}.root --x 6949000  -s "qcd" 
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_5080_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_5080_${version}.root --x  2201000 -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_80120_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_80120_${version}.root --x 415500  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_120170_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_120170_${version}.root --x 76140  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_170300_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_170300_${version}.root --x 18710  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_300Inf_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_300Inf_${version}.root --x 1220  -s "qcd"

hadd /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_2030_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_2030_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_2030_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_80120_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_120170_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_170300_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_300Inf_${version}.root

python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_2030_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_2030_${version}.root --x 363100  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_3080_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_3080_${version}.root --x 417800  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_80170_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_80170_${version}.root --x 39860  -s "qcd"
python2.6 weight_events.py --input_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_170250_${version}_unweighted.root --output_filename /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_170250_${version}.root --x 2608  -s "qcd"

hadd /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_2030_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_3080_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_80170_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_170250_${version}.root

hadd /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_electron_enriched_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_bctoe_${version}.root /afs/cern.ch/work/a/anlevin/data/fr_flattish_ntuples/qcd_em_enriched_${version}.root
