output_dir_wmwm=/afs/cern.ch/user/a/anlevin/www/VBS/20Apr2016/wmwm/
output_dir_wpwp=/afs/cern.ch/user/a/anlevin/www/VBS/20Apr2016/wpwp/

python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "diquark_mass" "diquark_mass" "m_{jj} (GeV)" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegmjj.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "lepton_pt" "lepton_pt" "p_{T}^{l} (GeV)" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegptl.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "lepton_eta" "lepton_eta" "\eta^l" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowheglepeta.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "quark_pt" "quark_pt" "p_{T}^{q} (GeV)" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegptq.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "quark_eta" "quark_eta" "\eta^q" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegquarketa.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "dilepton_mass" "dilepton_mass" "m_{ll}" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegmll.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "costheta1" "costheta1" "" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegcostheta1.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "costheta2" "costheta2" "" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegcostheta2.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "deltaetajj" "deltaetajj" "|\Delta \eta_{jj}|" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegdetajj.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "deltaetall" "deltaetall" "|\Delta \eta_{ll}|" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegdetall.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "deltaphijj" "deltaphijj" "|\Delta \phi_{jj}|" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegdphijj.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "deltaphill" "deltaphill" "|\Delta \phi_{ll}|" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegdphill.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wmwm.root" "output_distributions_powheg_wmwm.root" 1 1 1 1 1 "neutrinos_pt" "neutrinos_pt" "p_{T}^{\nu\nu}" "madgraph" "powheg" "${output_dir_wmwm}madgraphvspowhegneutrinospt.png" 0

python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "diquark_mass" "diquark_mass" "m_{jj} (GeV)" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegmjj.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "lepton_pt" "lepton_pt" "p_{T}^{l} (GeV)" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegptl.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "lepton_eta" "lepton_eta" "\eta^l" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowheglepeta.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "quark_pt" "quark_pt" "p_{T}^{q} (GeV)" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegptq.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "quark_eta" "quark_eta" "\eta^q" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegquarketa.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "dilepton_mass" "dilepton_mass" "m_{ll}" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegmll.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "costheta1" "costheta1" "" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegcostheta1.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "costheta2" "costheta2" "" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegcostheta2.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "deltaetajj" "deltaetajj" "|\Delta \eta_{jj}|" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegdetajj.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "deltaetall" "deltaetall" "|\Delta \eta_{ll}|" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegdetall.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "deltaphijj" "deltaphijj" "|\Delta \phi_{jj}|" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegdphijj.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "deltaphill" "deltaphill" "|\Delta \phi_{ll}|" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegdphill.png" 0
python2.6 plot_lhe_distributions.py "output_distributions_madgraph_wpwp.root" "output_distributions_powheg_wpwp.root" 1 1 1 1 1 "neutrinos_pt" "neutrinos_pt" "p_{T}^{\nu\nu}" "madgraph" "powheg" "${output_dir_wpwp}madgraphvspowhegneutrinospt.png" 0

